adding optional error throw

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,8 +1,8 @@
 name: CI
 on:
   pull_request:
-#    types: [labeled, synchronize]
-    types: [labeled]
+    types: [labeled, synchronize]
+#    types: [labeled]
     branches:
       - main
       
@@ -24,6 +24,12 @@ jobs:
           echo "GITHUB_REF:  $GITHUB_REF"
           echo "GITHUB_REPOSITORY:  $GITHUB_REPOSITORY"
           echo "GITHUB_SHA:  $GITHUB_SHA"
+      - name: optional error
+        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci:error') }}
+        run |
+          echo "Error Condition Being Raised Now"
+          exit 1
+
 #          sleep 1m
 #  minor:
 #    runs-on: ubuntu-latest
